create table principio_ativo (
	nomePA varchar(200)
)

insert into principio_ativo values
 ('Acetato De Lanreotida'),
 ('Aciclovir'),
 ('Actaea Racemosa L.'),
 ('Adalimumabe'),
 ('Amoxicilina Trihidratada'),
 ('Axetilcefuroxima'),
 ('Besilato De Cisatracúrio'),
 ('Betametasona'),
 ('Borago Officinalis L.'),
 ('Brivaracetam'),
 ('Cefazolina Sódica'),
 ('Cetoprofeno'),
 ('Citrato De Fentanila'),
 ('Citrato De Sódio Di-Hidratado'),
 ('Cladribina'),
 ('Cloreto De Potássio'),
 ('Cloreto De Sódio'),
 ('Colecalciferol'),
 ('Crizanlizumabe'),
 ('Fenilalamina'),
 ('Glicose'),
 ('Hemitartarato De Zolpidem'),
 ('Hialuronato De Sódio'),
 ('Hidroclorotiazida'),
 ('Inotersena Nonadecassódica'),
 ('Loratadina'),
 ('Montelucaste De Sódio'),
 ('Onasemnogeno Abeparvoveque'),
 ('Paracetamol'),
 ('Polatuzumabe Vedotina'),
 ('Pregabalina'),
 ('Sulfato De Magnésio Heptaidratado'),
 ('Valproato De Sódio'),
 ('Bromidrato De Vortioxetina'),
 ('Captopril'),
 ('Ceftriaxona Dissódica Hemieptaidratada'),
 ('Cepa Influenza Tipo B'),
 ('Cloreto De Tróspio'),
 ('Cloreto Férrico'),
 ('Cloridrato De Duloxetina'),
 ('Cloridrato De Fexofenadina'),
 ('Desloratadina'),
 ('Enoxaparina Sódica'),
 ('Epinefrina'),
 ('Etanercepte'),
 ('Fenilalanina'),
 ('Fumarato De Formoterol'),
 ('Inibidor De C1 Esterase Derivado De Plasma Humano'),
 ('Levetiracetam'),
 ('Levonorgestrel'),
 ('Meloxicam'),
 ('Metotrexato'),
 ('Pantoprazol Sódico Sesqui-Hidratado'),
 ('Semaglutida'),
 ('Imunoglobulina Humana'),
 ('Imunoglobulina G'),
 ('Filgrastim'),
 ('21-Acetato De Dexametasona'),
 ('Abacavir'),
 ('Abatacepte'),
 ('Abciximabe'),
 ('Abemaciclibe'),
 ('Acalabrutinibe'),
 ('Acarbose'),
 ('Acebrofilina'),
 ('Aceclofenaco'),
 ('Aceponato De Metilprednisolona'),
 ('Acetato De Abiraterona'),
 ('Acetato De Atosibana'),
 ('Acetato De Bazedoxifeno'),
 ('Acetato De Busserrelina'),
 ('Acetato De Caspofungina'),
 ('Acetato De Cetrorrelix'),
 ('Acetato De Ciproterona'),
 ('Acetato De Clormadinona'),
 ('Acetato De Degarelix'),
 ('Acetato De Desmopressina'),
 ('Acetato De Dexametasona'),
 ('Acetato De Fludrocortisona'),
 ('Acetato De Fluormetolona'),
 ('Acetato De Ganirrelix'),
 ('Acetato De Glatirâmer'),
 ('Acetato De Gosserrelina'),
 ('Acetato De Hidrocortisona'),
 ('Acetato De Icatibanto'),
 ('Acetato De Leuprorrelina'),
 ('Acetato De Medroxiprogesterona'),
 ('Acetato De Megestrol'),
 ('Acetato De Metilprednisolona'),
 ('Acetato De Nomegestrol'),
 ('Acetato De Noretisterona'),
 ('Acetato De Octreotida'),
 ('Acetato De Prednisolona'),
 ('Acetato De Racealfatocoferol'),
 ('Acetato De Retinol'),
 ('Acetato De Sódio Trihidratado'),
 ('Acetato De Sódio Triidratado'),
 ('Acetato De Terlipressina'),
 ('Acetato De Tocoferol'),
 ('Acetato De Triptorrelina'),
 ('Acetato De Ulipristal'),
 ('Acetazolamida'),
 ('Acetil-Levometionina'),
 ('Acetilcisteína'),
 ('Acetilracemetionina'),
 ('Acetonida De Triancinolona'),
 ('Aciclovir Sódico'),
 ('Ácido Acético Glacial'),
 ('Acido Acetilsalicilico'),
 ('Ácido Acetilsalicílico'),
 ('Ácido Aminocapróico'),
 ('Ácido Ascórbico'),
 ('Ácido Ascórbico 90%'),
 ('Ácido Azelaico'),
 ('Ácido Benzóico'),
 ('Ácido Carglúmico'),
 ('Acido Citrico'),
 ('Ácido Cítrico'),
 ('Ácido Desoxicólico'),
 ('Ácido Fólico'),
 ('Ácido Fusídico'),
 ('Ácido Gadotérico'),
 ('Ácido Gamaminobutírico'),
 ('Ácido Glicólico'),
 ('Ácido Hialurônico'),
 ('Ácido Ibandrônico'),
 ('Ácido Mefenâmico'),
 ('Ácido Nalidíxico'),
 ('Ácido Nicotínico'),
 ('Ácido Paraminobenzóico'),
 ('Ácido Salicílico'),
 ('Ácido Selenioso'),
 ('Ácido Tióctico'),
 ('Ácido Tranexâmico'),
 ('Ácido Ursodesoxicólico'),
 ('Ácido Valpróico'),
 ('Ácido Zoledrônico'),
 ('Ácido Zoledrônico Monoidratado'),
 ('Acitretina'),
 ('Adapaleno'),
 ('Adefovir Divipoxila'),
 ('Adenosina'),
 ('Aesculus Hippocastanum L.'),
 ('Aflibercepte'),
 ('Agomelatina'),
 ('Água Para Injeção'),
 ('Água Para Injeção Q.S.P.'),
 ('Água Para Injetáveis'),
 ('Água Para Injetáveis Qsp'),
 ('Alanilglutamina'),
 ('Alantoína'),
 ('Albendazol'),
 ('Albumina Humana'),
 ('Alcaftadina'),
 ('Álcool Polivinílico'),
 ('Alendronato De Sódio'),
 ('Alendronato De Sódio Tri-Hidratado'),
 ('Alentuzumabe'),
 ('Alfa-Albutrepenonacogue'),
 ('Alfa-Alglicosidase'),
 ('Alfa-Asfotase'),
 ('Alfa1antitripsina'),
 ('Alfacalcidol'),
 ('Alfacerliponase'),
 ('Alfacorifolitropina'),
 ('Alfacoriogonadotropina'),
 ('Alfadamoctocogue Pegol'),
 ('Alfadarbepoetina'),
 ('Alfadornase'),
 ('Alfaefmoroctocogue'),
 ('Alfaeftrenonacogue'),
 ('Alfaelosulfase'),
 ('Alfaepoetina'),
 ('Alfaeptacogue Ativado'),
 ('Alfaestradiol'),
 ('Alfafolitropina'),
 ('Alfagalsidase'),
 ('Alfainterferona 2a'),
 ('Alfainterferona 2b'),
 ('Alfalonoctocogue'),
 ('Alfalutropina'),
 ('Alfamoroctocogue'),
 ('Alfanonacogue'),
 ('Alfaoctocogue'),
 ('Alfapeginterferona 2a'),
 ('Alfapeginterferona 2b'),
 ('Alfaporactanto'),
 ('Alfarurioctocogue Pegol'),
 ('Alfasimoctocogue'),
 ('Alfassebelipase'),
 ('Alfataliglicerase'),
 ('Alfatirotropina'),
 ('Alfaturoctocogue'),
 ('Alfavelaglicerase'),
 ('Alfavelmanase'),
 ('Alfavestronidase'),
 ('Alirocumabe'),
 ('Aloína'),
 ('Alopurinol'),
 ('Alpelisibe'),
 ('Alprazolam'),
 ('Alprostadil'),
 ('Alprostadil Alfaciclodextrina'),
 ('Alteplase'),
 ('Ambrisentana'),
 ('Amidotrizoato Sódico'),
 ('Aminaftona'),
 ('Aminofilina'),
 ('Amissulprida'),
 ('Amorolfina'),
 ('Amoxicilina'),
 ('Amoxicilina Sódica'),
 ('Amoxicilina Tri-Hidratada'),
 ('Ampicilina'),
 ('Ampicilina Anidra'),
 ('Ampicilina Sódica'),
 ('Ananas Comosus (L.) Merril.'),
 ('Anastrozol'),
 ('Anatoxina Tetânica'),
 ('Anfotericina B'),
 ('Anidulafungina'),
 ('Antígeno De Superfície Da Hepatite B'),
 ('Antimoniato De Meglumina'),
 ('Apalutamida'),
 ('Apixabana'),
 ('Apremilaste'),
 ('Aprepitanto'),
 ('Aprotinina'),
 ('Aripiprazol'),
 ('Arnica Montana'),
 ('Asparaginase'),
 ('Aspartato De Arginina'),
 ('Aspartato De Ornitina'),
 ('Atalureno'),
 ('Atenolol'),
 ('Atezolizumabe'),
 ('Atorvastatina Cálcica'),
 ('Atropa Belladonna'),
 ('Avelumabe'),
 ('Axetil Cefuroxima'),
 ('Axitinibe'),
 ('Azacitidina'),
 ('Azatioprina'),
 ('Azilsartana Medoxomila Potássica'),
 ('Azitromicina'),
 ('Azitromicina Di-Hidratada'),
 ('Azitromicina Diidratada'),
 ('Azitromicina Monoidratada'),
 ('Aztreonam'),
 ('Bacillus Cereus'),
 ('Bacitracina Zíncica'),
 ('Bacitracina'),
 ('Baclofeno'),
 ('Bacopa Monnieri (L.) Wettst.'),
 ('Baricitinibe'),
 ('Basiliximab'),
 ('Belimumabe'),
 ('Belinostate'),
 ('Bendamustina'),
 ('Benfotiamina'),
 ('Benralizumabe'),
 ('Benzbromarona'),
 ('Benzeno'),
 ('Benzilpenicilina Benzatina'),
 ('Benzilpenicilina Potássica'),
 ('Benznidazol'),
 ('Benzoato De Alogliptina'),
 ('Benzoato De Benzila'),
 ('Benzoato De Rizatriptana'),
 ('Benzoato De Sódio'),
 ('Benzocaína'),
 ('Benzoilmetronidazol'),
 ('Beractanto'),
 ('Besilato De Anlodipino'),
 ('Besilato De Atracúrio'),
 ('Besilato De Levanlodipino'),
 ('Beta-Agalsidase'),
 ('Betacaroteno'),
 ('Betacipionato De Estradiol'),
 ('Betaepoetina'),
 ('Betaína'),
 ('Betainterferona 1a'),
 ('Betainterferona 1b'),
 ('Betaistina'),
 ('Betaoctocogue'),
 ('Betapeginterferona 1a'),
 ('Bevacizumabe'),
 ('Bezafibrato'),
 ('Bicalutamida'),
 ('Bicarbonato De Potássio'),
 ('Bicarbonato De Sódio'),
 ('Bilastina'),
 ('Bimatoprosta'),
 ('Biotina'),
 ('Bisacodil'),
 ('Bisglicinato Ferroso'),
 ('Bisoprolol'),
 ('Bissulfato De Clopidogrel'),
 ('Bitartarato De Metaraminol'),
 ('Blinatumomabe'),
 ('Borato De Sódio'),
 ('Bortezomibe'),
 ('Bosentana'),
 ('Bosentana Monoidratada'),
 ('Brentuximabe Vedotina'),
 ('Brexpiprazol'),
 ('Brigatinibe'),
 ('Brimonidina'),
 ('Brinzolamida'),
 ('Bromazepam'),
 ('Brometo De Glicopirrônio'),
 ('Brometo De Ipratrópio'),
 ('Brometo De N-Butilescopolamina'),
 ('Brometo De Otilônio'),
 ('Brometo De Pancurônio'),
 ('Brometo De Pinavério'),
 ('Brometo De Piridostigmina'),
 ('Brometo De Rocurônio'),
 ('Brometo De Tiotrópio'),
 ('Brometo De Tiotrópio Monoidratado'),
 ('Brometo De Umeclidínio'),
 ('Brometo De Vecurônio'),
 ('Bromidrato De Citalopram'),
 ('Bromidrato De Darifenacina'),
 ('Bromidrato De Dextrometorfano'),
 ('Bromidrato De Fenoterol'),
 ('Bromidrato De Galantamina'),
 ('Bromoprida'),
 ('Budesonida'),
 ('Budesonida Micronizada'),
 ('Bumetanida'),
 ('Buprenorfina'),
 ('Burosumabe'),
 ('Bussulfano'),
 ('Butil Brometo De Escopolamina'),
 ('Butilbrometo De Escopolamina'),
 ('Cabazitaxel'),
 ('Cabergolina'),
 ('Cafeína Anidra'),
 ('Cafeína'),
 ('Calcipotriol'),
 ('Calcitonina Sintética De Salmão'),
 ('Calcitriol'),
 ('Cambendazol'),
 ('Canabidiol'),
 ('Canagliflozina Hemi-Hidratada'),
 ('Canaquinumabe'),
 ('Candesartana Cilexetila'),
 ('Cânfora'),
 ('Cânfora (2-Bornanona)'),
 ('Cansilato De Sódio'),
 ('Capecitabina'),
 ('Capsaicina'),
 ('Carbacol'),
 ('Carbamazepina'),
 ('Carbidopa (Port. 344/98 Lista C 1)'),
 ('Carbocisteína'),
 ('Carbômer 340'),
 ('Carbômer'),
 ('Carbonato Cálcio'),
 ('Carbonato De Cálcio'),
 ('Carbonato De Cálcio 90%'),
 ('Carbonato De Lítio'),
 ('Carbonato De Lodenafila'),
 ('Carboplatina'),
 ('Carboximaltose Férrica'),
 ('Carboximetilcelulose Sódica'),
 ('Carfilzomibe'),
 ('Carisoprodol'),
 ('Carmelose Sódica'),
 ('Carmustina'),
 ('Carvão Vegetal Ativado'),
 ('Carvedilol'),
 ('Cassia Angustifolia, Vahl'),
 ('Cassia Senna L.'),
 ('Cefaclor'),
 ('Cefaclor Monoidratado'),
 ('Cefadroxila'),
 ('Cefalexina'),
 ('Cefalexina Monoidratada'),
 ('Cefalotina Sodica'),
 ('Cefotaxima Sódica'),
 ('Cefoxitina Sódica'),
 ('Ceftarolina Fosamila'),
 ('Ceftazidima'),
 ('Ceftazidima  Sodica'),
 ('Ceftazidima Pentaidratada'),
 ('Ceftriaxona'),
 ('Ceftriaxona Sódica'),
 ('Cefuroxima Sódica'),
 ('Celecoxibe'),
 ('Cemiplimabe'),
 ('Centella Asiatica (L.) Urb.'),
 ('Centella Asiatica Urb.'),
 ('Certolizumabe Pegol'),
 ('Cetoconazol'),
 ('Cetorolaco Trometamina'),
 ('Cetrimida'),
 ('Cetuximabe'),
 ('Cianocobalamina'),
 ('Ciclesonida'),
 ('Ciclobenzaprina'),
 ('Ciclofosfamida Monoidratada'),
 ('Ciclopirox'),
 ('Ciclopirox Olamina'),
 ('Ciclosporina'),
 ('Cilastatina Sódica'),
 ('Cilazapril'),
 ('Cilostazol'),
 ('Cimetidina'),
 ('Cinarizina'),
 ('Cinchona Calisaya Wedd.'),
 ('Cipionato De Testosterona'),
 ('Ciprofibrato'),
 ('Ciprofloxacino'),
 ('Cisplatina'),
 ('Citalopram'),
 ('Citarabina'),
 ('Citrato De Cafeína'),
 ('Citrato De Cálcio'),
 ('Citrato De Clomifeno'),
 ('Citrato De Colina'),
 ('Citrato De Ixazomibe'),
 ('Citrato De Orfenadrina'),
 ('Citrato De Pentoxiverina'),
 ('Citrato De Potássio'),
 ('Citrato De Potássio Monoidratado'),
 ('Citrato De Sildenafila'),
 ('Citrato De Sódio Dihidratado'),
 ('Citrato De Sódio'),
 ('Citrato De Sufentanila'),
 ('Citrato De Tamoxifeno'),
 ('Citrato De Tofacitinibe'),
 ('Citrato De Zinco Tri-Hidratado'),
 ('Claritromicina'),
 ('Clavulanato De Potássio'),
 ('Clioquinol'),
 ('Clobazam'),
 ('Clodronato Dissódico'),
 ('Clonazepam'),
 ('Clonixinato De Lisina'),
 ('Clopamida'),
 ('Clorambucila'),
 ('Cloranfenicol'),
 ('Clorato De Sódio'),
 ('Clordiazepóxido'),
 ('Cloreto De Amônio'),
 ('Cloreto De Benzalcônio'),
 ('Cloreto De Benzetônio'),
 ('Cloreto De Cálcio'),
 ('Cloreto De Cálcio 2h2o'),
 ('Cloreto De Cetilpiridínio'),
 ('Cloreto De Dequalínio'),
 ('Cloreto De Magnésio Hexaidratado'),
 ('Cloreto De Metiltionínio'),
 ('Cloreto De Oxibutinina'),
 ('Cloreto De Rádio (223 Ra)'),
 ('Cloreto De Sódio Usp'),
 ('Cloreto De Suxametônio'),
 ('Cloridrato  De Ondansetrona Di-Hidratado'),
 ('Cloridrato De Alectinibe'),
 ('Cloridrato De Alfentanila'),
 ('Cloridrato De Alfentanila Monoidratada'),
 ('Cloridrato De Alfuzosina'),
 ('Cloridrato De Alizaprida'),
 ('Cloridrato De Amantadina'),
 ('Cloridrato De Ambroxol'),
 ('Cloridrato De Amilorida'),
 ('Cloridrato De Aminolevulinato De Metila'),
 ('Cloridrato De Amiodarona'),
 ('Cloridrato De Amitriptilina'),
 ('Cloridrato De Amorolfina'),
 ('Cloridrato De Anagrelida'),
 ('Cloridrato De Azelastina'),
 ('Cloridrato De Bambuterol'),
 ('Cloridrato De Bamifilina'),
 ('Cloridrato De Benazepril'),
 ('Cloridrato De Benserazida'),
 ('Cloridrato De Benzidamina'),
 ('Cloridrato De Besifloxacino'),
 ('Cloridrato De Betaistina'),
 ('Cloridrato De Betaxolol'),
 ('Cloridrato De Biperideno'),
 ('Cloridrato De Bromexina'),
 ('Cloridrato De Bupivacaína'),
 ('Cloridrato De Bupropiona'),
 ('Cloridrato De Buspirona'),
 ('Cloridrato De Butenafina'),
 ('Cloridrato De Cefepima'),
 ('Cloridrato De Cetamina'),
 ('Cloridrato De Ciclobenzaprina'),
 ('Cloridrato De Ciclopentolato'),
 ('Cloridrato De Cimetidina'),
 ('Cloridrato De Cinacalcete'),
 ('Cloridrato De Ciproeptadina'),
 ('Cloridrato De Ciprofloxacino'),
 ('Cloridrato De Ciprofloxacino Monoidratado'),
 ('Cloridrato De Clindamicina'),
 ('Cloridrato De Clindamicina Monoidratado'),
 ('Cloridrato De Clomipramina'),
 ('Cloridrato De Clonidina'),
 ('Cloridrato De Clorpromazina'),
 ('Cloridrato De Daunorrubicina'),
 ('Cloridrato De Delapril'),
 ('Cloridrato De Dexmedetomidina'),
 ('Cloridrato De Dexrazoxano'),
 ('Cloridrato De Dextrocetamina'),
 ('Cloridrato De Difenidramina'),
 ('Cloridrato De Diltiazem'),
 ('Cloridrato De Dobutamina'),
 ('Cloridrato De Donepezila'),
 ('Cloridrato De Dopamina'),
 ('Cloridrato De Dorzolamida'),
 ('Cloridrato De Doxiciclina'),
 ('Cloridrato De Doxorrubicina'),
 ('Cloridrato De Epinastina'),
 ('Cloridrato De Epirrubicina'),
 ('Cloridrato De Erlotinibe'),
 ('Cloridrato De Esmolol'),
 ('Cloridrato De Etilefrina'),
 ('Cloridrato De Fenazopiridina'),
 ('Cloridrato De Fenilefrina'),
 ('Cloridrato De Fenoxazolina'),
 ('Cloridrato De Fingolimode'),
 ('Cloridrato De Fluoxetina'),
 ('Cloridrato De Flurazepam'),
 ('Cloridrato De Gencitabina'),
 ('Cloridrato De Granisetrona'),
 ('Cloridrato De Hidralazina'),
 ('Cloridrato De Hidroxizina'),
 ('Cloridrato De Hidroxocobalamina'),
 ('Cloridrato De Idarrubicina'),
 ('Cloridrato De Imipramina'),
 ('Cloridrato De Ioimbina'),
 ('Cloridrato De Irinotecano'),
 ('Cloridrato De Irinotecano Triidratado'),
 ('Cloridrato De Isotipendil'),
 ('Cloridrato De Isoxsuprina'),
 ('Cloridrato De Lercanidipino'),
 ('Cloridrato De Levamisol'),
 ('Cloridrato De Levobunolol'),
 ('Cloridrato De Levobupivacaína'),
 ('Cloridrato De Levomepromazina'),
 ('Cloridrato De Lidocaina'),
 ('Cloridrato De Lincomicina'),
 ('Cloridrato De Lisina'),
 ('Cloridrato De Loperamida'),
 ('Cloridrato De Lorcasserina Hemi-Hidratado'),
 ('Cloridrato De Lurasidona'),
 ('Cloridrato De Maprotilina'),
 ('Cloridrato De Mebeverina'),
 ('Cloridrato De Meclizina'),
 ('Cloridrato De Mefloquina'),
 ('Cloridrato De Memantina'),
 ('Cloridrato De Mepivacaína'),
 ('Cloridrato De Metadona'),
 ('Cloridrato De Metformina'),
 ('Cloridrato De Metilfenidato'),
 ('Cloridrato De Metoclopramida'),
 ('Cloridrato De Metoclopramida Monoidratado'),
 ('Cloridrato De Midazolam'),
 ('Cloridrato De Migalastate'),
 ('Cloridrato De Minociclina'),
 ('Cloridrato De Mitoxantrona'),
 ('Cloridrato De Moxifloxacino'),
 ('Cloridrato De Nafazolina'),
 ('Cloridrato De Nalbufina'),
 ('Cloridrato De Naloxona'),
 ('Cloridrato De Naltrexona'),
 ('Cloridrato De Naratriptana'),
 ('Cloridrato De Nebivolol'),
 ('Cloridrato De Nortriptilina'),
 ('Cloridrato De Olodaterol'),
 ('Cloridrato De Olopatadina'),
 ('Cloridrato De Ondansetrona'),
 ('Cloridrato De Oxibuprocaína'),
 ('Cloridrato De Oxibutinina'),
 ('Cloridrato De Oxicodona'),
 ('Cloridrato De Oximetazolina'),
 ('Cloridrato De Oxitetraciclina'),
 ('Cloridrato De Palonosetrona'),
 ('Cloridrato De Papaverina'),
 ('Cloridrato De Paroxetina'),
 ('Cloridrato De Paroxetina Hemi-Hidratado'),
 ('Cloridrato De Pazopanibe'),
 ('Cloridrato De Petidina'),
 ('Cloridrato De Pilocarpina'),
 ('Cloridrato De Pioglitazona'),
 ('Cloridrato De Piridoxina'),
 ('Cloridrato De Ponatinibe'),
 ('Cloridrato De Prasugrel'),
 ('Cloridrato De Prazosina'),
 ('Cloridrato De Prilocaína'),
 ('Cloridrato De Procaína'),
 ('Cloridrato De Prometazina'),
 ('Cloridrato De Propafenona'),
 ('Cloridrato De Propranolol'),
 ('Cloridrato De Protamina'),
 ('Cloridrato De Proximetacaína'),
 ('Cloridrato De Pseudoefedrina'),
 ('Cloridrato De Raloxifeno'),
 ('Cloridrato De Ranitidina'),
 ('Cloridrato De Remifentanila'),
 ('Cloridrato De Ropivacaína'),
 ('Cloridrato De Selegilina'),
 ('Cloridrato De Sertralina'),
 ('Cloridrato De Sevelamer'),
 ('Cloridrato De Sibutramina'),
 ('Cloridrato De Sibutramina Monoidratado'),
 ('Cloridrato De Sotalol'),
 ('Cloridrato De Tansulosina'),
 ('Cloridrato De Tapentadol'),
 ('Cloridrato De Terbinafina'),
 ('Cloridrato De Tetracaína'),
 ('Cloridrato De Tetraciclina'),
 ('Cloridrato De Tiamina'),
 ('Cloridrato De Ticlopidina'),
 ('Cloridrato De Tioridazina'),
 ('Cloridrato De Tirofiban Monoidratado'),
 ('Cloridrato De Tizanidina'),
 ('Cloridrato De Topotecana'),
 ('Cloridrato De Tramadol'),
 ('Cloridrato De Trazodona'),
 ('Cloridrato De Triexifenidil'),
 ('Cloridrato De Valaciclovir'),
 ('Cloridrato De Valganciclovir'),
 ('Cloridrato De Vancomicina'),
 ('Cloridrato De Vardenafila'),
 ('Cloridrato De Venlafaxina'),
 ('Cloridrato De Verapamil'),
 ('Cloridrato De Vilazodona'),
 ('Cloridrato De Xilometazolina'),
 ('Cloridrato De Ziprasidona'),
 ('Cloridrato De Ziprasidona Monoidratado'),
 ('Clorpropamida'),
 ('Clortalidona'),
 ('Clotrimazol'),
 ('Cloxazolam'),
 ('Clozapina'),
 ('Coaltar'),
 ('Colagenase'),
 ('Colchicina'),
 ('Colestiramina'),
 ('Complexo Protrombínico Humano Liofilizado'),
 ('Complexo Protrombínico Parcialmente Ativado'),
 ('Condroitina Sulfato De Sódio'),
 ('Cordia Verbenacea Dc.'),
 ('Crataegus Rhipidophylla Gand.'),
 ('Crizotinibe'),
 ('Cromoglicato De Sodio'),
 ('Curcuma Longa L.'),
 ('Cynara Scolymus L.'),
 ('Dabigatrana'),
 ('Dacarbazina'),
 ('Dalteparina Sódica'),
 ('Danazol'),
 ('Dantroleno Sódico'),
 ('Dapagliflozina'),
 ('Dapsona'),
 ('Daptomicina'),
 ('Daratumumabe'),
 ('Darolutamida'),
 ('Darunavir'),
 ('Dasatinibe'),
 ('Dasatinibe Monoidratado'),
 ('Decanoato De Haloperidol'),
 ('Decanoato De Nandrolona'),
 ('Decanoato De Testosterona'),
 ('Decitabina'),
 ('Deferasirox'),
 ('Deferiprona'),
 ('Defibrotida'),
 ('Deflazacorte'),
 ('Deltafolitropina'),
 ('Deltametrina'),
 ('Denosumabe'),
 ('Derisomaltose Férrica'),
 ('Desflurano'),
 ('Deslanosídeo'),
 ('Desogestrel'),
 ('Desonida'),
 ('Desoximetasona'),
 ('Dexametasona'),
 ('Dexclorfeniramina'),
 ('Dexlansoprazol'),
 ('Dexpantenol'),
 ('Dextrana'),
 ('Diacereína'),
 ('Diatrizoato De Meglumina'),
 ('Diazepam'),
 ('Diazóxido'),
 ('Diclofenaco'),
 ('Diclofenaco Colestiramina'),
 ('Diclofenaco De Potássio'),
 ('Diclofenaco De Sódio'),
 ('Diclofenaco Dietilamônio'),
 ('Diclofenaco Potássico'),
 ('Diclofenaco Sódico'),
 ('Dicloridrato De Betaistina'),
 ('Dicloridrato De Buclizina'),
 ('Dicloridrato De Cetirizina'),
 ('Dicloridrato De Daclatasvir'),
 ('Dicloridrato De Etambutol'),
 ('Dicloridrato De Flufenazina'),
 ('Dicloridrato De Flunarizina'),
 ('Dicloridrato De Hidroxizina'),
 ('Dicloridrato De Levocetirizina'),
 ('Dicloridrato De Manidipino'),
 ('Dicloridrato De Meclozina Monoidratado'),
 ('Dicloridrato De Pramipexol'),
 ('Dicloridrato De Pramipexol Monoidratado'),
 ('Dicloridrato De Sapropterina'),
 ('Dicloridrato De Trifluoperazina'),
 ('Dicloridrato De Trimetazidina'),
 ('Didrogesterona'),
 ('Dienogeste'),
 ('Dietilestilbestrol'),
 ('Difosfato De Cloroquina'),
 ('Digoxina'),
 ('Diltiazem'),
 ('Dimaleato De Afatinibe'),
 ('Dimenidrinato'),
 ('Dimesilato De Lisdexanfetamina'),
 ('Dimeticona'),
 ('Dimetilsulfóxido De Trametinibe'),
 ('Dinitrato De Isossorbida'),
 ('Dinoprostona'),
 ('Diosmina'),
 ('Dipiridamol'),
 ('Dipirona'),
 ('Dipirona  Magnésica'),
 ('Dipirona Monoidratada'),
 ('Dipropionato De Beclometasona'),
 ('Dipropionato De Betametasona'),
 ('Dissulfiram'),
 ('Ditosilato De Lapatinibe'),
 ('Divalproato De Sódio'),
 ('Dobesilato De Cálcio'),
 ('Docetaxel'),
 ('Docetaxel Triidratado'),
 ('Docetaxol'),
 ('Docusato De Sódio'),
 ('Dolutegravir Sódico'),
 ('Domperidona'),
 ('Doxiciclina Monoidratada'),
 ('Droperidol'),
 ('Dropropizina'),
 ('Drospirenona'),
 ('Dulaglutida'),
 ('Dupilumabe'),
 ('Durvalumabe'),
 ('Dutasterida'),
 ('Ebastina'),
 ('Echinacea Purpurea (L.) Moench'),
 ('Eculizumabe'),
 ('Edoxabana'),
 ('Efavirenz'),
 ('Elbasvir'),
 ('Elotuzumabe'),
 ('Eltrombopague Olamina'),
 ('Embonato De Pirvínio'),
 ('Emicizumabe'),
 ('Empagliflozina'),
 ('Enantato De Estradiol'),
 ('Enantato De Flufenazina'),
 ('Enantato De Noretisterona'),
 ('Enflurano'),
 ('Enfuvirtida'),
 ('Entacapona'),
 ('Entecavir'),
 ('Entecavir Monoidratado'),
 ('Enzalutamida'),
 ('Erdafitinibe'),
 ('Erenumabe'),
 ('Ergotamina'),
 ('Eritromicina'),
 ('Eritropoetina Humana Recombinante'),
 ('Eritropoietina'),
 ('Erlotinibe'),
 ('Ertapeném Sódico'),
 ('Esilato De Nintedanibe'),
 ('Esomeprazol Magnésico'),
 ('Esomeprazol Magnésico Tri-Hidratado'),
 ('Esomeprazol Magnésio'),
 ('Esomeprazol Sódico'),
 ('Esomeprazol'),
 ('Espiramicina'),
 ('Espironolactona'),
 ('Estavudina'),
 ('Estazolam'),
 ('Ésteres Etílicos Dos Ácidos Graxos Do Óleo De Papoula Iodados'),
 ('Estolato De Eritromicina'),
 ('Estradiol'),
 ('Estradiol Hemi-Hidratado'),
 ('Estreptoquinase'),
 ('Estriol'),
 ('Estrogênios Conjugados'),
 ('Eszopiclona'),
 ('Etabonato De Loteprednol'),
 ('Etanolato De Darunavir'),
 ('Etinilestradiol'),
 ('Etionamida'),
 ('Etodolaco'),
 ('Etomidato'),
 ('Etonogestrel'),
 ('Etoposídeo'),
 ('Etoricoxibe'),
 ('Etossuximida'),
 ('Etravirina'),
 ('Eucalipto'),
 ('Eucaliptus Globulus  Labill'),
 ('Everolimo'),
 ('Evolocumabe'),
 ('Exemestano'),
 ('Exenatida'),
 ('Extrato Da Semente De Glycine Soja (Soja)'),
 ('Extrato De Aesculus Hippocastanum (Castanha-Da-Índia)'),
 ('Extrato De Gentiana Lutea'),
 ('Extrato De Ginkgo Biloba'),
 ('Extrato De Hedera Helix (Hera)'),
 ('Extrato De Symphytum Officinale'),
 ('Extrato Fluido De Agrião (Nasturtium Officinale)'),
 ('Extrato Seco De Aesculus Hippocastanum L.'),
 ('Extrato Seco De Hypericum Perforatum L'),
 ('Extrato Seco De Passiflora'),
 ('Extrato Seco De Valeriana Officinalis L.'),
 ('Extratos Alergênicos De Insetos Sugadores'),
 ('Ezetimiba'),
 ('Famotidina'),
 ('Fampridina'),
 ('Fanciclovir'),
 ('Fator De Von Willebrand'),
 ('Fator Ix De Coagulação'),
 ('Fator Viii De Coagulação'),
 ('Fator X'),
 ('Fator Xiii De Coagulação'),
 ('Felodipino'),
 ('Fendizoato De Cloperastina'),
 ('Fenilbutazona Cálcica'),
 ('Fenitoína'),
 ('Fenitoína Sódica'),
 ('Fenobarbital'),
 ('Fenobarbital Sódico'),
 ('Fenofibrato'),
 ('Fenofibratos Microgrânulos A 75%'),
 ('Fenoximetilpenicilina Potássica'),
 ('Fentanila'),
 ('Ferededato De Sódio'),
 ('Ferripolimaltose'),
 ('Ferro Aminoacido Quelato'),
 ('Ferrocarbonila'),
 ('Fibrinogênio'),
 ('Finasterida'),
 ('Fitomenadiona'),
 ('Fluconazol'),
 ('Flumazenil'),
 ('Flunarizina'),
 ('Flunitrazepam'),
 ('Fluocinolona Acetonida'),
 ('Fluormetolona'),
 ('Fluoruracila'),
 ('Fluoxetina'),
 ('Flurandrenolida'),
 ('Flurbiprofeno'),
 ('Flurbiprofeno Sódico'),
 ('Flutamida'),
 ('Flutrimazol'),
 ('Fluvastatina Sódica'),
 ('Folinato De Cálcio'),
 ('Fondaparinux Sódico'),
 ('Fosamprenavir'),
 ('Fosamprenavir Cálcico'),
 ('Fosaprepitanto Dimeglumina'),
 ('Fosfato De Cálcio Dibásico Di-Hidratado'),
 ('Fosfato De Cálcio Dibásico'),
 ('Fosfato De Cálcio Tribásico'),
 ('Fosfato De Clindamicina'),
 ('Fosfato De Codeína'),
 ('Fosfato De Fludarabina'),
 ('Fosfato De Oseltamivir'),
 ('Fosfato De Potássio Dibásico'),
 ('Fosfato De Ruxolitinibe'),
 ('Fosfato De Sitagliptina'),
 ('Fosfato De Sódio Dibásico Di-Hidratado'),
 ('Fosfato De Sódio Dibásico Diidratado'),
 ('Fosfato De Sódio Monobásico Monoidratado'),
 ('Fosfato De Sódio Monobásico'),
 ('Fosfato De Tedizolida'),
 ('Fosfato De Tetraciclina'),
 ('Fosfato Dissódico De Betametasona'),
 ('Fosfato Dissódico De Dexametasona'),
 ('Fosfato Sódico De Prednisolona'),
 ('Fosfomicina Trometamol'),
 ('Fotemustina'),
 ('Fremanezumabe'),
 ('Frutose'),
 ('Fucus Vesiculosus L.'),
 ('Fulvestranto'),
 ('Fumarato De Cetotifeno'),
 ('Fumarato De Clemastina'),
 ('Fumarato De Dimetila'),
 ('Fumarato De Formoterol Di-Hidratado'),
 ('Fumarato De Formoterol Diidratado'),
 ('Fumarato De Rupatadina'),
 ('Fumarato De Tenofovir Desoproxila'),
 ('Fumarato De Vonoprazana'),
 ('Fumarato Ferroso'),
 ('Furoato De Fluticasona'),
 ('Furoato De Mometasona'),
 ('Furoato De Mometasona Monoidratado'),
 ('Furosemida'),
 ('Fusafungina'),
 ('Gabapentina'),
 ('Gadobenato De Dimeglumina'),
 ('Gadobutrol'),
 ('Gadodiamida'),
 ('Gadopentetato De Dimeglumina'),
 ('Gadoteridol'),
 ('Gadoversetamida'),
 ('Gadoxetato Dissódico'),
 ('Galcanezumabe'),
 ('Galsulfase'),
 ('Gamanonacogue'),
 ('Ganciclovir'),
 ('Ganciclovir Sódico'),
 ('Gangliosídeo Gm1'),
 ('Garcinia Cambogia Roxb.'),
 ('Gatifloxacino'),
 ('Gatifloxacino Sesqui-Hidratado'),
 ('Gefitinibe'),
 ('Gelatina'),
 ('Gemifloxacino'),
 ('Genfibrozila'),
 ('Gestodeno'),
 ('Ginkgo Biloba L.'),
 ('Givosirana Sódica'),
 ('Glibenclamida'),
 ('Glicerina Bidestilada'),
 ('Glicerofosfato De Cálcio'),
 ('Glicerofosfato De Sódio'),
 ('Glicerol'),
 ('Glicina'),
 ('Glicinato De Alumínio'),
 ('Glicinato De Magnésio'),
 ('Glicinato De Zinco'),
 ('Glicinato Férrico'),
 ('Gliclazida'),
 ('Gliconato De Cálcio'),
 ('Gliconato De Clorexidina'),
 ('Gliconato De Zinco'),
 ('Glicose Anidra'),
 ('Glicose Monoidratada'),
 ('Glimepirida'),
 ('Glipizida'),
 ('Glucagon'),
 ('Glutamina'),
 ('Glycine Max'),
 ('Glycine Max (L.) Merr.'),
 ('Golimumabe'),
 ('Gonadotrofina Coriônica'),
 ('Griseofulvina'),
 ('Guaiacol'),
 ('Guaifenesina'),
 ('Guselcumabe'),
 ('Haloperidol'),
 ('Halotano'),
 ('Hamamelis Virginiana L.'),
 ('Harpagophytum Procumbens (Burch.) Dc. Ex Meissn.'),
 ('Harpagophytum Procumbens Dc. Ex Meissn.'),
 ('Hedera Helix (Hera)'),
 ('Hedera Helix L.'),
 ('Hemaglutinina Filamentosa'),
 ('Hemifumarato De Alisquireno'),
 ('Hemifumarato De Bisoprolol'),
 ('Hemifumarato De Cobimetinibe'),
 ('Hemifumarato De Gilteritinibe'),
 ('Hemifumarato De Quetiapina'),
 ('Hemifumarato De Tenofovir Alafenamida'),
 ('Hemina'),
 ('Hemitartarato De Eliglustate'),
 ('Hemitartarato De Epinefrina'),
 ('Hemitartarato De Norepinefrina'),
 ('Hemitartarato De Rivastigmina'),
 ('Hemitartarato De Vinorelbina'),
 ('Heparina Sódica Bovina'),
 ('Heparina Sódica Suína'),
 ('Heparina Suína'),
 ('Hesperidina'),
 ('Hexacetonido De Triancinolona'),
 ('Hexafluoreto De Enxofre'),
 ('Hialuronidase'),
 ('Hiclato De Doxiciclina'),
 ('Hidrocortisona'),
 ('Hidrogenotartarato De Rivastigmina'),
 ('Hidroquinona'),
 ('Hidrosmina'),
 ('Hidroxibenzoato De Viminol'),
 ('Hidroxicarbamida'),
 ('Hidróxido De Alumínio'),
 ('Hidróxido De Magnésio'),
 ('Hidroxietilamido'),
 ('Hidroxinaftoato De Salmeterol'),
 ('Hidroxipropil Guar'),
 ('Hidroxiquinolina'),
 ('Hidroxiuréia'),
 ('Hidroxizina'),
 ('Hidroxocobalamina'),
 ('Himatanthus Lancifolius'),
 ('Hipofosfito De Sódio'),
 ('Hipromelose'),
 ('Hypericum Perforatum'),
 ('Hypericum Perforatum L.'),
 ('Ibandronato De Sódio'),
 ('Ibandronato De Sódio Monoidratado'),
 ('Ibrutinibe'),
 ('Ibuprofeno'),
 ('Ibuprofeno Arginina'),
 ('Icodextrina'),
 ('Idarucizumabe'),
 ('Idursulfase'),
 ('Ifosfamida'),
 ('Iloprosta'),
 ('Imiglucerase'),
 ('Imipeném Monoidratado'),
 ('Imipeném'),
 ('Imiquimode'),
 ('Imunoglobulina Anti-D'),
 ('Imunoglobulina Anti-Rábica'),
 ('Imunoglobulina Anti-Rho(D)'),
 ('Imunoglobulina Antitetânica'),
 ('Imunoglobulina De Coelho Anti-Timócitos Humanos'),
 ('Imunoglobulina Heteróloga Contra Toxina Botulínica Tipo B'),
 ('Imunoglobulina Heteróloga Contra Veneno De Bothrops Sp'),
 ('Imunoglobulina Heteróloga Contra Veneno De Crotalus Sp'),
 ('Imunoglobulina Heteróloga Contra Veneno De Lonomia Obliqua'),
 ('Imunoglobulina Heteróloga Contra Veneno De Micrurus Frontalis'),
 ('Imunoglobulina Heteróloga Contra Veneno De Phoneutria Nigriventer'),
 ('Imunoglobulina Heteróloga Contra Veneno De Tityus Serrulatus'),
 ('Imunoglobulina Humana Anti-Hepatite B'),
 ('Indapamida'),
 ('Indometacina'),
 ('Infliximabe'),
 ('Inotuzumabe Ozogamicina'),
 ('Insulina Asparte'),
 ('Insulina Degludeca'),
 ('Insulina Detemir'),
 ('Insulina Glargina'),
 ('Insulina Glulisina'),
 ('Insulina Humana'),
 ('Insulina Isofana'),
 ('Insulina Lispro'),
 ('Interleucina'),
 ('Iobitridol'),
 ('Iodeto De Potássio'),
 ('Iodixanol'),
 ('Iodo Povidona Pvpi'),
 ('Iodo'),
 ('Ioexol'),
 ('Iomeprol'),
 ('Ion Citrato'),
 ('Iopamidol'),
 ('Iopromida'),
 ('Ioversol'),
 ('Ipilimumabe'),
 ('Irbesartana'),
 ('Isoconazol'),
 ('Isoflurano'),
 ('Isometepteno'),
 ('Isoniazida'),
 ('Isotretinoína'),
 ('Itraconazol'),
 ('Ivabradina'),
 ('Ivacaftor'),
 ('Ivermectina'),
 ('Ixequizumabe'),
 ('L-Prolina'),
 ('L-Treonina'),
 ('Lacidipino'),
 ('Lacosamida'),
 ('Lactato De Biperideno'),
 ('Lactato De Milrinona'),
 ('Lactato De Sódio'),
 ('Lactulose'),
 ('Lamivudina'),
 ('Lamotrigina'),
 ('Lanadelumabe'),
 ('Lansoprazol'),
 ('Laronidase'),
 ('Latanoprosta'),
 ('Laurilsulfato De Sódio'),
 ('Lecitina De Ovo'),
 ('Leflunomida'),
 ('Lenalidomida'),
 ('Lesinurade'),
 ('Letrozol'),
 ('Leucina'),
 ('Levedura'),
 ('Levocetirizina'),
 ('Levodropropizina'),
 ('Levofloxacino'),
 ('Levofloxacino Hemi-Hidratado'),
 ('Levofloxacino Hemidratado (A Excluir)'),
 ('Levofloxacino Hemiidratado'),
 ('Levomalato De Cabozantinibe'),
 ('Levomentol'),
 ('Levometionina'),
 ('Levonorgestrel Micronizado'),
 ('Levosimendana'),
 ('Levotiroxina Sódica'),
 ('Lidocaína'),
 ('Limeciclina'),
 ('Linagliptina'),
 ('Linezolida'),
 ('Lipegfilgrastim'),
 ('Liraglutida'),
 ('Lisado Bacteriano'),
 ('Lisado Bacteriano De Escherichia Coli'),
 ('Lisados Bacterianos (Staphylococcus Aureus, Streptococcus Pyogenes, Streptococcus Mitis, Streptococcus Pneumoniae, Klebsiella Pneumoniae, Branhamella Catarrhalis, Haemophilus Influenzae)'),
 ('Lisados Bacterianos (Staphylococcus Aureus, Streptococcus Pyogenes, Streptococcus Mitis, Streptococcus Pneumoniae,Klebsiella Pneumoniae, Branhamella Catarrhalis, Haemophilus Influenzae)'),
 ('Lisinato De Cetoprofeno'),
 ('Lisinato De Clonixina'),
 ('Lisinopril'),
 ('Lixisenatida'),
 ('Lomustina'),
 ('Loperamida'),
 ('Lopinavir'),
 ('Lorazepam'),
 ('Lorlatinibe'),
 ('Lornoxicam'),
 ('Losartana Potássica'),
 ('Lovastatina'),
 ('Loxoprofeno Sódico'),
 ('Loxoprofeno Sódico Diidratado'),
 ('Lubiprostona'),
 ('Lumacaftor'),
 ('Macrogol'),
 ('Magaldrato'),
 ('Malato De Sunitinibe'),
 ('Maleato Ácido De Timolol'),
 ('Maleato De Asenapina'),
 ('Maleato De Bronfeniramina'),
 ('Maleato De Clorfenamina'),
 ('Maleato De Clorfeniramina'),
 ('Maleato De Dexbronfeniramina'),
 ('Maleato De Dexclorfeniramina'),
 ('Maleato De Enalapril'),
 ('Maleato De Ergometrina'),
 ('Maleato De Feniramina'),
 ('Maleato De Fluvoxamina'),
 ('Maleato De Indacaterol'),
 ('Maleato De Levomepromazina'),
 ('Maleato De Metilergometrina'),
 ('Maleato De Midazolam'),
 ('Maleato De Tegaserode'),
 ('Maleato De Timolol'),
 ('Maleato De Trimebutina'),
 ('Manitol'),
 ('Maraviroque'),
 ('Maytenus Ilicifolia Mart. Ex Reissek'),
 ('Maytenus Ilicifolia Mart.Ex.Reiss'),
 ('Mebendazol'),
 ('Mebutato De Ingenol'),
 ('Meclozina'),
 ('Mecobalamina'),
 ('Meglumina'),
 ('Melfalana'),
 ('Melilotus Officinalis (L.) Pall.'),
 ('Melilotus Officinalis Lam.'),
 ('Memantina'),
 ('Menaeptenona'),
 ('Menotropina'),
 ('Mentha Crispa L.'),
 ('Mentol'),
 ('Mepivacaína'),
 ('Mepolizumabe'),
 ('Mercaptopurina'),
 ('Meropeném'),
 ('Meropeném Tri-Hidratado'),
 ('Mesilato De Bromocriptina'),
 ('Mesilato De Codergocrina'),
 ('Mesilato De Dabrafenibe'),
 ('Mesilato De Deferoxamina'),
 ('Mesilato De Di-Hidroergotamina'),
 ('Mesilato De Diidroergocristina'),
 ('Mesilato De Doxazosina'),
 ('Mesilato De Eribulina'),
 ('Mesilato De Imatinibe'),
 ('Mesilato De Lenvatinibe'),
 ('Mesilato De Osimertinibe'),
 ('Mesilato De Rasagilina'),
 ('Mesilato De Safinamida'),
 ('Mesilato Sódico De Colistina'),
 ('Mesna'),
 ('Messalazina'),
 ('Mesterolona'),
 ('Metenamina'),
 ('Metilbrometo De Homatropina'),
 ('Metildigoxina'),
 ('Metildopa'),
 ('Metildopa Sesquiidratado'),
 ('Metilprednisolona'),
 ('Metilsulfato De Neostigmina'),
 ('Metimazol'),
 ('Metoclopramida'),
 ('Metoxisaleno'),
 ('Metronidazol'),
 ('Metronidazol Benzoil'),
 ('Micafungina'),
 ('Micofenolato De Mofetila'),
 ('Micofenolato De Sódio'),
 ('Miconazol'),
 ('Midazolam'),
 ('Midostaurina'),
 ('Mifamurtida'),
 ('Miglustate'),
 ('Mikania Glomerata Spreng.'),
 ('Minoxidil'),
 ('Mirabegrona'),
 ('Mirtazapina'),
 ('Misoprostol'),
 ('Mitotano'),
 ('Modafinila'),
 ('Monofosfato De Riboflavina'),
 ('Monofosfato De Riboflavina Sódica'),
 ('Mononitrato De Isossorbida'),
 ('Mononitrato De Tiamina'),
 ('Monossulfiram'),
 ('Montelucaste'),
 ('Mucato De Isometepteno'),
 ('Mucopolissacaridase'),
 ('Mupirocina'),
 ('Naproxeno'),
 ('Naproxeno Sódico'),
 ('Nasturtium Officinale R.Br.'),
 ('Natalizumabe'),
 ('Nateglinida'),
 ('Nc/Ni'),
 ('Nepafenaco'),
 ('Nevirapina'),
 ('Nicergolina'),
 ('Nicotina'),
 ('Nicotinamida'),
 ('Nifedipino'),
 ('Nilotinibe'),
 ('Nimesulida'),
 ('Nimesulida Betaciclodextrina'),
 ('Nimodipino'),
 ('Nimotuzumabe'),
 ('Nistatina'),
 ('Nitazoxanida'),
 ('Nitisinona'),
 ('Nitrato Ceroso'),
 ('Nitrato De Butoconazol'),
 ('Nitrato De Fenticonazol'),
 ('Nitrato De Isoconazol'),
 ('Nitrato De Miconazol'),
 ('Nitrato De Nafazolina'),
 ('Nitrato De Oxiconazol'),
 ('Nitrato De Tiamina'),
 ('Nitrazepam'),
 ('Nitrendipino'),
 ('Nitrofural'),
 ('Nitrofurantoína'),
 ('Nitrofurazona'),
 ('Nitroglicerina'),
 ('Nitroprusseto De Sódio'),
 ('Nitroprusseto De Sódio Di-Hidratado'),
 ('Nivolumabe'),
 ('Norelgestromina'),
 ('Noretisterona'),
 ('Norfloxacino'),
 ('Nusinersena'),
 ('Obinutuzumabe'),
 ('Ocitocina'),
 ('Ocrelizumabe'),
 ('Octreotida'),
 ('Ofloxacino'),
 ('Olanzapina'),
 ('Olaparibe'),
 ('Olaratumabe'),
 ('Oleato De Monoetanolamina'),
 ('Óleo De Eucalipto'),
 ('Óleo De Fígado De Bacalhau'),
 ('Óleo De Peixe'),
 ('Óleo De Soja'),
 ('Oligossacarídeo Meningocócico Y'),
 ('Olmesartana Medoxomila'),
 ('Olopatadina'),
 ('Omalizumabe'),
 ('Omeprazol'),
 ('Omeprazol Magnésico'),
 ('Omeprazol Sódico'),
 ('Operculina Alata (Ham.) Urb.'),
 ('Orlipastat'),
 ('Orlistate'),
 ('Oryza Sativa L.'),
 ('Oxacilina Sódica'),
 ('Oxalato De Escitalopram'),
 ('Oxaliplatina'),
 ('Oxcarbazepina'),
 ('Oxetacaína'),
 ('Óxido Cúprico'),
 ('Óxido De Magnésio'),
 ('Óxido De Zinco'),
 ('Paclitaxel'),
 ('Palbociclibe'),
 ('Paliperidona'),
 ('Palivizumabe'),
 ('Palmitato De Paliperidona'),
 ('Palmitato De Retinol'),
 ('Palonosetrona'),
 ('Pamidronato Dissódico'),
 ('Panax Ginseng C.'),
 ('Pancreatina'),
 ('Panitumumabe'),
 ('Pantoprazol'),
 ('Pantoprazol Magnésico Di-Hidratado'),
 ('Pantoprazol Sódico'),
 ('Pantoprazol Sódico Sesqui-Hiidratado'),
 ('Pantotenato De C'),
 ('Papaver Somniferum L.'),
 ('Parecoxibe Sódico'),
 ('Paricalcitol'),
 ('Partícula Semelhante A Vírus De Proteína L1 Do Hpv Do Tipo 58'),
 ('Passiflora Incarnata'),
 ('Passiflora Incarnata L.'),
 ('Pegaspargase'),
 ('Pegfilgrastim'),
 ('Pegvisomanto'),
 ('Pelargonium Sidoides Dc.'),
 ('Pembrolizumabe'),
 ('Pemetrexede Dissódico'),
 ('Pemetrexede Dissódico Hemipentaidratado'),
 ('Pemetrexede Dissódico Heptaidratado'),
 ('Penciclovir'),
 ('Penicilamina'),
 ('Penicilina G Benzatina'),
 ('Pentoxifilina'),
 ('Perampanel'),
 ('Periciazina'),
 ('Perindopril'),
 ('Perindopril Arginina'),
 ('Perindopril Erbumina'),
 ('Permetrina'),
 ('Peróxido De Benzoíla'),
 ('Peroxido De Benzoila'),
 ('Peróxido De Uréia'),
 ('Peróxido De Zinco'),
 ('Persea Americana Mill.'),
 ('Pertactina'),
 ('Pertuzumabe'),
 ('Petrolato Líquido'),
 ('Peumus Boldus'),
 ('Pibrentasvir'),
 ('Picossulfato De Sódio'),
 ('Picossulfato De Sódio Monoidratado'),
 ('Pidolato De Piridoxina'),
 ('Pimecrolimo'),
 ('Pimozida'),
 ('Pindolol'),
 ('Pinus Pinaster Aiton'),
 ('Piper Methysticum'),
 ('Piperacilina Sódica'),
 ('Piperacilina'),
 ('Piracetam'),
 ('Pirazinamida'),
 ('Pirenoxina Sódica'),
 ('Pirfenidona'),
 ('Piridoxina'),
 ('Pirimetamina'),
 ('Piroxicam'),
 ('Piroxicam Betaciclodextrina'),
 ('Pitavastatina Cálcica'),
 ('Plantago Ovata Forssk.'),
 ('Plantago Ovata Phil.'),
 ('Plerixafor'),
 ('Poliacrilamidometil Benzilideno Cânfora'),
 ('Poliaminoácidos'),
 ('Policarbofila'),
 ('Policresuleno'),
 ('Poliestirenossulfonato De Cálcio'),
 ('Poliovírus Tipo 3'),
 ('Polissacarídeo'),
 ('Polissacarídeo Capsular De Streptococcus Pneumoniae Sorotipo 9v'),
 ('Polissacarídeo De Haemophilus Influenzae Tipo B Conjugado Com Proteína Tetânica'),
 ('Polissacarideo De Haemophilus Influenzae Tipo B'),
 ('Polissacarídeo De Neisseria Meningitidis Do Sorogrupo A Conjugado A Proteína Carreadora Toxoide Tetânico'),
 ('Polissacarídeo De Neisseria Meningitidis Do Sorogrupo W Conjugado A Proteína Carreadora Toxoide Tetânico'),
 ('Polissulfato De Mucopolissacarídeo'),
 ('Polivitamínicos Com Minerais'),
 ('Polygala Senega L.'),
 ('Polypodium Leucotomos'),
 ('Posaconazol'),
 ('Pravastatina Sódica'),
 ('Praziquantel'),
 ('Prednicarbato'),
 ('Prednisolona'),
 ('Prednisona'),
 ('Primidona'),
 ('Progesterona'),
 ('Promestrieno'),
 ('Prometazina'),
 ('Propatilnitrato'),
 ('Propilparabeno'),
 ('Propiltiouracila'),
 ('Propionato De Cálcio'),
 ('Propionato De Clobetasol'),
 ('Propionato De Fluticasona'),
 ('Propionato De Halobetasol'),
 ('Propofol'),
 ('Proteína Antigênica De Superfície (Hep. B)'),
 ('Proteínas'),
 ('Prucaloprida'),
 ('Rabeprazol Sódico'),
 ('Racealfatocoferol'),
 ('Racecadotrila'),
 ('Racemetionina'),
 ('Raltegravir'),
 ('Raltegravir Potássico'),
 ('Ramelteona'),
 ('Ramipril'),
 ('Ramucirumabe'),
 ('Ranelato De Estrôncio'),
 ('Ranibizumabe'),
 ('Ranolazina'),
 ('Rasburicase'),
 ('Reboxetina'),
 ('Regorafenibe'),
 ('Repaglinida'),
 ('Resinato De Diclofenaco'),
 ('Retapamulina'),
 ('Rhamnus Purshiana Dc.'),
 ('Ribavirina (Port. 344/98 Lista C 1)'),
 ('Riboflavina'),
 ('Rifamicina'),
 ('Rifamicina Sv Sódica'),
 ('Rifampicina'),
 ('Rifaximina'),
 ('Rilmenidina'),
 ('Riluzol'),
 ('Riociguate'),
 ('Risanquizumabe'),
 ('Risedronato Sódico'),
 ('Risperidona'),
 ('Ritonavir'),
 ('Rituximabe'),
 ('Rivaroxabana'),
 ('Rivastigmina'),
 ('Roflumilaste'),
 ('Romiplostim'),
 ('Rosuvastatina'),
 ('Rosuvastatina Cálcica'),
 ('Rotigotina'),
 ('Rufinamida'),
 ('Rutosídeo'),
 ('Sacarato De Hidróxido Férrico'),
 ('Sacarato De Óxido Férrico'),
 ('Saccharomyces Boulardii'),
 ('Saccharomyces Boulardii - 17'),
 ('Saccharomyces Cerevisae'),
 ('Salbutamol'),
 ('Salicilato De Dietilamônio'),
 ('Salicilato De Metila'),
 ('Salix Alba L.'),
 ('Saxagliptina'),
 ('Secnidazol'),
 ('Secuquinumabe'),
 ('Selênio'),
 ('Selexipague'),
 ('Senna Alexandrina Mill.'),
 ('Serenoa Repens (W. Bartram) Small'),
 ('Sevoflurano'),
 ('Silimarina'),
 ('Siltuximabe'),
 ('Silybum Marianum (L.) Gaertn'),
 ('Simeprevir Sódico'),
 ('Simeticona'),
 ('Sinvastatina'),
 ('Sirolimo'),
 ('Sofosbuvir'),
 ('Solidago Microglossa Dc.'),
 ('Somatostatina'),
 ('Somatropina'),
 ('Sorbitol'),
 ('Stryphnodendron Barbatiman Mart.'),
 ('Subcitrato De Bismuto Coloidal'),
 ('Subgalato De Bismuto'),
 ('Succinato De Desvenlafaxina Monoidratado'),
 ('Succinato De Doxilamina'),
 ('Succinato De Metoprolol'),
 ('Succinato De Ribociclibe'),
 ('Succinato De Solifenacina'),
 ('Succinato De Sumatriptana'),
 ('Succinato De Tafenoquina'),
 ('Succinato Sódico De Cloranfenicol'),
 ('Succinato Sódico De Hidrocortisona'),
 ('Succinato Sódico De Metilprednisolona'),
 ('Succinilgelatina'),
 ('Sucralfato'),
 ('Sugamadex Sódico'),
 ('Sulbactam'),
 ('Sulbactam Pivoxila'),
 ('Sulbactam Sódico'),
 ('Sulbutiamina'),
 ('Sulfacetamida Sódica'),
 ('Sulfadiazina'),
 ('Sulfadiazina De Prata'),
 ('Sulfametoxazol'),
 ('Sulfassalazina'),
 ('Sulfato Cúprico Pentaidratado'),
 ('Sulfato De Abacavir'),
 ('Sulfato De Amicacina'),
 ('Sulfato De Atazanavir'),
 ('Sulfato De Atropina'),
 ('Sulfato De Bário'),
 ('Sulfato De Bleomicina'),
 ('Sulfato De Condroitina'),
 ('Sulfato De Efedrina'),
 ('Sulfato De Estreptomicina'),
 ('Sulfato De Gentamicina'),
 ('Sulfato De Glicosamina'),
 ('Sulfato De Hidroxicloroquina'),
 ('Sulfato De Isavuconazônio'),
 ('Sulfato De Larotrectinibe'),
 ('Sulfato De Magnésio'),
 ('Sulfato De Morfina'),
 ('Sulfato De Morfina Pentaidratado'),
 ('Sulfato De Neomicina'),
 ('Sulfato De Polimixina B'),
 ('Sulfato De Quinina'),
 ('Sulfato De Salbutamol'),
 ('Sulfato De Terbutalina'),
 ('Sulfato De Tobramicina'),
 ('Sulfato De Trimetoprima'),
 ('Sulfato De Tuaminoeptano'),
 ('Sulfato De Vimblastina'),
 ('Sulfato De Vincristina'),
 ('Sulfato De Zinco'),
 ('Sulfato De Zinco Heptaidratado'),
 ('Sulfato De Zinco Monoidratado'),
 ('Sulfato Ferroso'),
 ('Sulfato Ferroso Heptaidratado'),
 ('Sulfato Policristalino De Glicosamina'),
 ('Sulfeto De Selênio'),
 ('Sulpirida'),
 ('Sultamicilina'),
 ('Sumatriptana'),
 ('Tacrolimo'),
 ('Tacrolimo Monoidratado'),
 ('Tadalafila'),
 ('Tafamidis Meglumina'),
 ('Tafluprosta'),
 ('Talidomida'),
 ('Tanacetum Parthenium (L.) Sch.Bip.'),
 ('Tartarato De Bismuto E Sódio'),
 ('Tartarato De Brimonidina'),
 ('Tartarato De Metoprolol'),
 ('Tartarato De Tolterodina'),
 ('Tartarato De Vareniclina'),
 ('Taurina'),
 ('Tazobactam Sódico'),
 ('Teclozana'),
 ('Teduglutida'),
 ('Teicoplanina'),
 ('Telmisartana'),
 ('Temozolomida'),
 ('Tenecteplase'),
 ('Teniposídeo'),
 ('Tenoxicam'),
 ('Tensirolimo'),
 ('Teofilina'),
 ('Terconazol'),
 ('Teriflunomida'),
 ('Teriparatida'),
 ('Terpina Monoidratada'),
 ('Testosterona'),
 ('Tiabendazol'),
 ('Tianeptina'),
 ('Tianeptina Sódica'),
 ('Tianfenicol'),
 ('Tibolona'),
 ('Ticagrelor'),
 ('Tigeciclina'),
 ('Timoestimulina'),
 ('Timol'),
 ('Timomodulina'),
 ('Tinidazol'),
 ('Tiocolchicosídeo'),
 ('Tioconazol'),
 ('Tioguanina'),
 ('Tiopental Sódico'),
 ('Tipranavir'),
 ('Tirofibana'),
 ('Tirotricina'),
 ('Tobramicina'),
 ('Tocilizumabe'),
 ('Tolcapona'),
 ('Topiramato'),
 ('Tosilato De Sorafenibe'),
 ('Tosilato De Sultamicilina'),
 ('Toxina Botulínica A'),
 ('Toxóide Diftérico'),
 ('Tranilcipromina'),
 ('Trastuzumabe'),
 ('Travoprosta'),
 ('Tretinoína'),
 ('Triancinolona Acetonida'),
 ('Tribenosídeo'),
 ('Tribulus Terrestris L.'),
 ('Triclosana'),
 ('Trifenatato De Vilanterol'),
 ('Trifluridina'),
 ('Trifolium Pratense L.'),
 ('Trifosfato Dissódico De Uridina'),
 ('Triglicerídios C10-18'),
 ('Trimegestona'),
 ('Trimetoprima'),
 ('Trióxido De Arsênio'),
 ('Triptorrelina'),
 ('Trombina'),
 ('Trometamol Cetorolaco'),
 ('Tropicamida'),
 ('Troxerrutina'),
 ('Uncaria Tomentosa Dc.'),
 ('Undecilato De Testosterona'),
 ('Upadacitinibe Hemi-Hidratado'),
 ('Uréia'),
 ('Uridina-5''-Trifosfato Trissódica'),
 ('Uridina'),
 ('Urofolitropina'),
 ('Ustequinumabe'),
 ('Vacina Adsorvida Difteria, Tétano E Pertussis'),
 ('Vacina Adsorvida Difteria, Tétano E Pertussis (Acelular)'),
 ('Vacina Adsorvida Difteria, Tétano, Pertussis (Acelular), Hepatite B (Recombinante), Poliomielite 1, 2 E 3 (Inativada) E Haemophilus Influenzae B (Conjugada)'),
 ('Vacina Adsorvida Difteria, Tétano, Pertussis (Acelular), Poliomielite 1, 2 E 3 (Inativada)'),
 ('Vacina Adsorvida Difteria, Tétano, Pertussis (Acelular), Poliomielite 1, 2 E 3 (Inativada) E Haemophilus Influenzae B (Conjugada)'),
 ('Vacina Adsorvida Hepatite A (Inativada)'),
 ('Vacina Adsorvida Meningocócica B (Recombinante)'),
 ('Vacina Bcg'),
 ('Vacina Contra Raiva'),
 ('Vacina Contra Sarampo'),
 ('Vacina Dengue 1, 2, 3 E 4 (Recombinante, Atenuada)'),
 ('Vacina Haemophilus Influenzae B (Conjugada) E Meningocócica C (Conjugada)'),
 ('Vacina Hepatite B (Recombinante)'),
 ('Vacina Herpes Zoster (Atenuada)'),
 ('Vacina Influenza Tetravalente (Fragmentada, Inativada)'),
 ('Vacina Influenza Tetravalente (Inativada, Subunitária)'),
 ('Vacina Influenza Trivalente (Fragmentada, Inativada)'),
 ('Vacina Influenza Trivalente (Inativada, Fracionada)'),
 ('Vacina Influenza Trivalente (Inativada, Subunitária)'),
 ('Vacina Influenza Trivalente (Inativada, Subunitária),Vacina Influenza Trivalente (Inativada, Subunitária, Adjuvada)'),
 ('Vacina Meningocócica Acwy (Conjugada)'),
 ('Vacina Meningogócica Conjugada Do Grupo C'),
 ('Vacina Papilomavírus Humano 16 E 18 (Recombinante)'),
 ('Vacina Papilomavírus Humano 6, 11, 16 E 18 (Recombinante)'),
 ('Vacina Pneumocócica 10-Valente (Conjugada)'),
 ('Vacina Pneumocócica 13-Valente (Conjugada)'),
 ('Vacina Pneumocócica 23-Valente (Polissacarídica)'),
 ('Vacina Raiva (Inativada)'),
 ('Vacina Rotavírus Humano G1 P1 [8] (Atenuada)'),
 ('Vacina Rotavírus Humano/Bovino G1, G2, G3, G4 E P1 [8] (Atenuada)'),
 ('Vacina Sarampo, Caxumba, Rubéola (Atenuada)'),
 ('Vacina Sarampo, Caxumba, Rubéola E Varicela (Atenuada)'),
 ('Vacina Tétano (Inativada)'),
 ('Vacina Varicela (Atenuada)'),
 ('Valerato De Betametasona'),
 ('Valerato De Diflucortolona'),
 ('Valerato De Estradiol'),
 ('Valerato De Estradiol Micronizado'),
 ('Valeriana Officinalis L.'),
 ('Valganciclovir'),
 ('Valsartana'),
 ('Vandetanibe'),
 ('Varfarina Sódica'),
 ('Vasopressina Sintetica'),
 ('Vedolizumabe'),
 ('Velpatasvir'),
 ('Vemurafenibe'),
 ('Venetoclax'),
 ('Verteporfina'),
 ('Vigabatrina'),
 ('Vildagliptina'),
 ('Vimpocetina'),
 ('Vinflunina'),
 ('Vinorelbina'),
 ('Vírus 17d Da Febre Amarela'),
 ('Vírus Da Caxumba'),
 ('Vírus Da Hepatite A Purificado Inativado'),
 ('Virus Da Varicela'),
 ('Vírus Da Varicela -Zoster'),
 ('Vírus Quimérico Febre Amarela Dengue Sorotipo 4'),
 ('Vismodegibe'),
 ('Vitamina B1'),
 ('Vitamina D'),
 ('Vitamina E'),
 ('Vitelinato De Prata'),
 ('Vitex Agnus-Castus L.'),
 ('Vitis Vinifera L.'),
 ('Voretigeno Neparvoveque'),
 ('Voriconazol'),
 ('Zanamivir'),
 ('Zidovudina'),
 ('Zingiber Officinale Roscoe'),
 ('Ziprasidona'),
 ('Zolmitriptana'),
 ('Zopiclona'),
 ('Zuclopentixol');

